import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.scss';
import { ApolloWrapper, Header } from './components';
import { ApolloProvider } from '@apollo/client';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rick and Morty GQL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <div className={styles.rootLayout}>
            <Header />
            <div className={styles.layout}>
              {children}
            </div>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  )
}
